version: '3'
services:
  webapp:
    image: node:10-alpine
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: sh -c "yarn install && yarn dev"
    ports:
      - "3030:3030"

  # chrome:
  #   image: selenium/node-chrome-debug:latest
  #   environment:
  #     - HUB_PORT_4444_TCP_ADDR=hub
  #     - HUB_PORT_4444_TCP_PORT=4444
  #   ports:
  #     - 5900:5900
  #   depends_on:
  #     - hub
  #   networks:
  #     - selenium-grid

  # hub:
  #   image: selenium/hub:latest
  #   expose:
  #     - 4444
  #   networks:
  #     - selenium-grid

networks:
  selenium-grid:

volumes:
  node_modules:
